config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  # Defines the root path route ("/")
  root "website/pages#homepage"

  namespace :admin, path: "/admin" do
    get "/", to: "pages#home"
    resources :contacts
    resources :users
  end

  namespace :dashboard, path: "/dashboard" do
    get "/", to: "pages#home"
    resources :blog_posts
    resources :portfolios
    resources :tags
    resources :tasks
    resources :technologies
    resources :users, only: %i[show edit]
  end

  namespace :website, path: "/" do
    get "/", to: "pages#homepage"
    get    "/blog"          => "blog_posts#index"
    get    "/blog/:id"      => "blog_posts#show", as: :show_blog
    resources :contacts, only: %i[new create]
    resources :portfolios, only: %i[index show]
  end

  # ATTACHMENTS
  delete "attachments/:id/purge", to: "attachments#purge", as: :purge_attachment
  get "attachments/:id", to: "attachments#show", as: :show_attachment
end

app/controllers/website/blog_posts_controller.rb
# frozen_string_literal: true

class Website::BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.published
  end

  def show
    @blog_post = BlogPost.friendly.find(params[:id])
  end
end

app/controllers/website/contacts_controller.rb
# frozen_string_literal: true

class Website::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: "Message sent. I will get back to you as soon as possible."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(
      :name,
      :email,
      :phone_number,
      :origin,
      :message
    )
  end
end

app/controllers/website/pages_controller.rb
# frozen_string_literal: true

class Website::PagesController < ApplicationController
  def homepage
  end
end

app/controllers/website/portfolios_controller.rb
# frozen_string_literal: true

module Website
  class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: [:show]

    def index
      @portfolios = Portfolio.published.includes([:technologies]).order(:position)
    end

    def show
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end
  end
end

app/views/website/shared/_header.html.erb
<header class="absolute inset-x-0 top-0 z-50">
  <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-3xl">
        <span class="sr-only">Your Company</span>
        <a href="/" class="-m-1.5 p-1.5">CRUD@Cloud</a>
      </h1>
    </div>
    <div class="flex lg:hidden" data-controller="dropdown">
      <button type="button" data-action="dropdown#toggle click@window->dropdown#hide"
              class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Open main menu</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"/>
        </svg>
      </button>

      <div
        data-dropdown-target="menu"
        class="hidden transition transform origin-top-right absolute right-0"
        data-transition-enter-from="opacity-0 scale-95"
        data-transition-enter-to="opacity-100 scale-100"
        data-transition-leave-from="opacity-100 scale-100"
        data-transition-leave-to="opacity-0 scale-95"
      >
        <div class="inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
          <div class="flex items-center justify-between">
            <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-3xl">
              <span class="sr-only">Crud in the Cloud</span>
              <a href="/" class="-m-1.5 p-1.5">CRUD@Cloud</a>
            </h1>
          </div>
          <div class="mt-6 flow-root">
            <div class="-my-6 divide-y divide-gray-500/10">
              <div class="space-y-2 py-6">
                <a href="<%= website_blog_path %>" data-action="dropdown#toggle"
                   class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  Blog
                </a>
                <a href="<%= website_portfolios_path %>" data-action="dropdown#toggle"
                   class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  Projects
                </a>
                <a href="/" data-action="dropdown#toggle"
                   class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  About
                </a>
              </div>
              <div class="py-6">
                <% if user_signed_in? %>
                  <%= link_to dashboard_path, class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold
                                                        leading-7 text-gray-900 hover:bg-gray-50" do %>
                    Dashboard <span aria-hidden="true">&rarr;</span>
                  <% end %>
                <% else %>
                  <%= link_to user_session_path, class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold
                                                        leading-7 text-gray-900 hover:bg-gray-50" do %>
                    Log in <span aria-hidden="true">&rarr;</span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="hidden lg:flex lg:gap-x-12">
      <%# TODO: Remove if statement when blog posts are published %>
      <%= link_to "Blog", website_blog_path, class: "hover:underline underline-offset-4 text-lg font-light leading-10 text-gray-900" if !BlogPost.published.count.zero? %>
      <a href="<%= website_portfolios_path %>" class="hover:underline underline-offset-4 text-lg font-light leading-10 text-gray-900">Projects</a>
      <a href="/" class="hover:underline underline-offset-4 text-lg font-light leading-10 text-gray-900">About</a>
    </div>
    <div class="hidden lg:flex lg:flex-1 lg:justify-end">
      <% if user_signed_in? %>
        <%= link_to dashboard_path, class: "hover:underline underline-offset-4" do %>
          Dashboard <span aria-hidden="true">&rarr;</span>
        <% end %>
      <% else %>
        <%= link_to user_session_path, class: "hover:underline underline-offset-4" do %>
          Log in <span aria-hidden="true">&rarr;</span>
        <% end %>
      <% end %>
    </div>
  </nav>
</header>