config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  # Defines the root path route ("/")
  root "website/pages#homepage"

  namespace :admin, path: "/admin" do
    get "/", to: "pages#home"
    resources :contacts
    resources :users
  end

  namespace :dashboard, path: "/dashboard" do
    get "/", to: "pages#home"
    resources :blog_posts
    resources :portfolios
    resources :tags
    resources :tasks
    resources :technologies
    resources :users, only: %i[show edit]
  end

  namespace :website, path: "/" do
    get "/", to: "pages#homepage"
    get    "/blog"          => "blog_posts#index"
    get    "/blog/:id"      => "blog_posts#show", as: :show_blog
    resources :contacts, only: %i[new create]
    resources :portfolios, only: %i[index show]
  end

  # ATTACHMENTS
  delete "attachments/:id/purge", to: "attachments#purge", as: :purge_attachment
  get "attachments/:id", to: "attachments#show", as: :show_attachment
end

app/models/technology.rb
# frozen_string_literal: true

class Technology < ApplicationRecord
  has_and_belongs_to_many :portfolios

  validates :name, presence: true, uniqueness: true
end

# == Schema Information
#
# Table name: technologies
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/dashboard/blog_posts_controller.rb
# frozen_string_literal: true

class Dashboard::BlogPostsController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_blog_post, only: %i[show edit update destroy]

  def index
    @blog_posts = BlogPost.for_user(current_user.id)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to dashboard_blog_posts_path, notice: "Blog post created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to dashboard_blog_post_path(@blog_post), notice: "The blog post has been updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @blog_post.destroy
      redirect_to dashboard_blog_posts_path, notice: "The blog_post has been deleted."
    else
      redirect_to dashboard_blog_posts_path, alert: "The blog_post has NOT been deleted."
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(
      :title,
      :body,
      :status,
      :user_id,
      tag_ids: [],
      tags_attributes: [:name]
    )
  end
end

app/controllers/dashboard/pages_controller.rb
# frozen_string_literal: true

class Dashboard::PagesController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!

  def home
  end
end

app/controllers/dashboard/portfolios_controller.rb
# frozen_string_literal: true

module Dashboard
  class PortfoliosController < ApplicationController
    layout "dashboard"

    before_action :authenticate_user!
    before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

    def index
      @portfolios = Portfolio.for_user(current_user.id).includes([:technologies]).order(:position)
    end

    def new
      @portfolio = Portfolio.new
    end

    def create
      @portfolio = Portfolio.new(portfolio_params)

      if @portfolio.save
        redirect_to dashboard_portfolios_path, notice: "Your Portfolio has been added."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def show
    end

    def update
      respond_to do |format|
        if @portfolio.update(portfolio_params)
          format.html { redirect_to dashboard_portfolio_path(@portfolio), notice: "Your Portfolio has been updated." }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @portfolio.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_portfolios_path, notice: "The Portfolio has been deleted!" }
      end
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :image,
        :live_link,
        :staging_link,
        :published,
        :position,
        :user_id,
        technology_ids: [],
        technologies_attributes: [:name]
      )
    end
  end
end

app/controllers/dashboard/tags_controller.rb
# frozen_string_literal: true

class Dashboard::TagsController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_tag, only: [:update, :destroy]

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def update
    @tag.update!(tag_params)
  end

  def destroy
    @tag.destroy!
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/dashboard/tasks_controller.rb
# frozen_string_literal: true

class Dashboard::TasksController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_task, only: [:update, :destroy]

  def index
    @tasks = Task.for_user(current_user)
  end

  def create
    @task = Task.create(task_params)
    @task.created_by = current_user
    @task.assigned_to = current_user
    @task.save
  end

  def update
    @task.update!(task_params)
  end

  def destroy
    @task.destroy!
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :completed, :created_by, :assigned_to)
  end
end

app/controllers/dashboard/technologies_controller.rb
# frozen_string_literal: true

module Dashboard
  class TechnologiesController < ApplicationController
    layout "dashboard"

    before_action :authenticate_user!
    before_action :set_technology, only: [:show, :edit, :update, :destroy]

    def index
      @technologies = Technology.all
    end

    def show
    end

    def edit
    end

    def create
      @technology = Technology.new(technology_params)
      if @technology.save
        redirect_back fallback_location: dashboard_technologies_path, notice: "The Technology has been added."
      else
        redirect_back fallback_location: dashboard_technologies_path, alert: "The Technology has NOT been added."
      end

    end

    def update
      @technology.update!(technology_params)
    end

    def destroy
      @technology.destroy!
    end

    private

    def set_technology
      @technology = Technology.find(params[:id])
    end

    def technology_params
      params.require(:technology).permit(:name)
    end
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

class Dashboard::UsersController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorized_users, only: %i[edit update destroy]

  def show
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to dashboard_user_path(@user), notice: "The user has been updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path, notice: "The user has been deleted."
    else
      redirect_to dashboard_users_path, alert: "The user has NOT been deleted."
    end
  end

  private

  def authorized_users
    unless current_user == @user
      redirect_to dashboard_path, alert: "No can do buddy."
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :avatar,
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
    )
  end
end

app/helpers/dashboard/page_helper.rb
module Dashboard::PageHelper
end

app/views/dashboard/technologies/_form.html.erb
<%= simple_form_for [:dashboard, technology], html: { class: "flex items-center max-w-xl" } do |f| %>
  <%= f.input :name,
              label: false,
              placeholder: "Enter technology name",
              wrapper_html: { class: "w-full" },
              input_html: {
                class: "form-field"
              }
  %>
  <%= f.button :submit, class: "submit-btn ml-2" %>
<% end %>

app/views/dashboard/technologies/_technology.html.erb
<div class="mt-3 max-w-xl">
  <ul>
    <li id="<%= dom_id(technology) %>" class="flex justify-between">
      <span>
        <%= technology.name %>
      </span>
      <span>
        <%= button_to dashboard_technology_path(technology.id), method: :delete,
                      form: { data: { turbo_confirm: "Are you sure?" } } do %>
          <%= heroicon "x-circle",
                       options: {
                         class: "p-1 w-6 h-6 inline-block text-white bg-red-600 rounded cursor-pointer",
                         disable_default_class: true
                       }
          %>
        <% end %>
      </span>
    </li>
  </ul>
</div>

app/views/dashboard/technologies/create.turbo_stream.erb
<%= turbo_stream.append "technologies-list",
                        partial: "dashboard/technologies/technology",
                        locals: { technology: @technology } %>

<%= turbo_stream.update "new-technology",
                        partial: "dashboard/technologies/form",
                        locals: { technology: Technology.new } %>

app/views/dashboard/technologies/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@technology) %>

app/views/dashboard/technologies/index.html.erb
<ul class="technologies" id="new-technology">
  <%= render partial: "form", locals: { technology: Technology.new } %>
</ul>
<ul id="technologies-list" class="technologies">
  <%= render partial: "dashboard/technologies/technology", collection: @technologies %>
</ul>

app/views/dashboard/technologies/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@technology),  partial: "dashboard/technologies/technology",  locals: { technology: @technology } %>