config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  # Defines the root path route ("/")
  root "website/pages#homepage"

  namespace :admin, path: "/admin" do
    get "/", to: "pages#home"
    resources :contacts
    resources :users
  end

  namespace :dashboard, path: "/dashboard" do
    get "/", to: "pages#home"
    resources :blog_posts
    resources :portfolios
    resources :tags
    resources :tasks
    resources :technologies
    resources :users, only: %i[show edit]
  end

  namespace :website, path: "/" do
    get "/", to: "pages#homepage"
    get    "/blog"          => "blog_posts#index"
    get    "/blog/:id"      => "blog_posts#show", as: :show_blog
    resources :contacts, only: %i[new create]
    resources :portfolios, only: %i[index show]
  end

  # ATTACHMENTS
  delete "attachments/:id/purge", to: "attachments#purge", as: :purge_attachment
  get "attachments/:id", to: "attachments#show", as: :show_attachment
end

app/models/portfolio.rb
# frozen_string_literal: true

class Portfolio < ApplicationRecord
  include Placeholder

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :subtitle, :body, :position

  belongs_to :user

  has_and_belongs_to_many :technologies

  scope :for_user, ->(user_id) { where(user_id: user_id) }

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 200]
  end

  has_many_attached :photos

  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs["name"].blank? }

  scope :published, -> { where(published: true) }

  def should_generate_new_friendly_id?
    title_changed?
  end
end

# == Schema Information
#
# Table name: portfolios
#
#  id           :bigint           not null, primary key
#  body         :text
#  live_link    :string
#  position     :integer
#  published    :boolean          default(FALSE)
#  slug         :string
#  staging_link :string
#  subtitle     :string
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_portfolios_on_slug     (slug) UNIQUE
#  index_portfolios_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

app/controllers/dashboard/blog_posts_controller.rb
# frozen_string_literal: true

class Dashboard::BlogPostsController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_blog_post, only: %i[show edit update destroy]

  def index
    @blog_posts = BlogPost.for_user(current_user.id)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to dashboard_blog_posts_path, notice: "Blog post created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to dashboard_blog_post_path(@blog_post), notice: "The blog post has been updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @blog_post.destroy
      redirect_to dashboard_blog_posts_path, notice: "The blog_post has been deleted."
    else
      redirect_to dashboard_blog_posts_path, alert: "The blog_post has NOT been deleted."
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(
      :title,
      :body,
      :status,
      :user_id,
      tag_ids: [],
      tags_attributes: [:name]
    )
  end
end

app/controllers/dashboard/pages_controller.rb
# frozen_string_literal: true

class Dashboard::PagesController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!

  def home
  end
end

app/controllers/dashboard/portfolios_controller.rb
# frozen_string_literal: true

module Dashboard
  class PortfoliosController < ApplicationController
    layout "dashboard"

    before_action :authenticate_user!
    before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

    def index
      @portfolios = Portfolio.for_user(current_user.id).includes([:technologies]).order(:position)
    end

    def new
      @portfolio = Portfolio.new
    end

    def create
      @portfolio = Portfolio.new(portfolio_params)

      if @portfolio.save
        redirect_to dashboard_portfolios_path, notice: "Your Portfolio has been added."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def show
    end

    def update
      respond_to do |format|
        if @portfolio.update(portfolio_params)
          format.html { redirect_to dashboard_portfolio_path(@portfolio), notice: "Your Portfolio has been updated." }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @portfolio.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_portfolios_path, notice: "The Portfolio has been deleted!" }
      end
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :image,
        :live_link,
        :staging_link,
        :published,
        :position,
        :user_id,
        technology_ids: [],
        technologies_attributes: [:name]
      )
    end
  end
end

app/controllers/dashboard/tags_controller.rb
# frozen_string_literal: true

class Dashboard::TagsController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_tag, only: [:update, :destroy]

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def update
    @tag.update!(tag_params)
  end

  def destroy
    @tag.destroy!
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/dashboard/tasks_controller.rb
# frozen_string_literal: true

class Dashboard::TasksController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_task, only: [:update, :destroy]

  def index
    @tasks = Task.for_user(current_user)
  end

  def create
    @task = Task.create(task_params)
    @task.created_by = current_user
    @task.assigned_to = current_user
    @task.save
  end

  def update
    @task.update!(task_params)
  end

  def destroy
    @task.destroy!
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :completed, :created_by, :assigned_to)
  end
end

app/controllers/dashboard/technologies_controller.rb
# frozen_string_literal: true

module Dashboard
  class TechnologiesController < ApplicationController
    layout "dashboard"

    before_action :authenticate_user!
    before_action :set_technology, only: [:show, :edit, :update, :destroy]

    def index
      @technologies = Technology.all
    end

    def show
    end

    def edit
    end

    def create
      @technology = Technology.new(technology_params)
      if @technology.save
        redirect_back fallback_location: dashboard_technologies_path, notice: "The Technology has been added."
      else
        redirect_back fallback_location: dashboard_technologies_path, alert: "The Technology has NOT been added."
      end

    end

    def update
      @technology.update!(technology_params)
    end

    def destroy
      @technology.destroy!
    end

    private

    def set_technology
      @technology = Technology.find(params[:id])
    end

    def technology_params
      params.require(:technology).permit(:name)
    end
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

class Dashboard::UsersController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorized_users, only: %i[edit update destroy]

  def show
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to dashboard_user_path(@user), notice: "The user has been updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path, notice: "The user has been deleted."
    else
      redirect_to dashboard_users_path, alert: "The user has NOT been deleted."
    end
  end

  private

  def authorized_users
    unless current_user == @user
      redirect_to dashboard_path, alert: "No can do buddy."
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :avatar,
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
    )
  end
end

app/controllers/website/portfolios_controller.rb
# frozen_string_literal: true

module Website
  class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: [:show]

    def index
      @portfolios = Portfolio.published.includes([:technologies]).order(:position)
    end

    def show
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end
  end
end

app/helpers/dashboard/page_helper.rb
module Dashboard::PageHelper
end

app/views/dashboard/portfolios/_form.html.erb
<%= simple_form_for [:dashboard, @portfolio], html: { class: "p-4" }, local: true do |f| %>
  <%= render "shared/form_errors", object: @portfolio %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="w-full flex items-center gap-4">
    <div class="w-96">
      <%= f.text_field :title, class: "form-field", placeholder: "Title of the project" %>
    </div>
    <div class="w-96">
      <%= f.text_field :subtitle, class: "form-field", placeholder: "Subtitle" %>
    </div>
    <div class="flex items-center">
      <%= f.check_box :published, as: :boolean, label: true,
                        input_html: { class: "form-field" } %>
      <div class="flex flex-col ml-2">
        <label for="published" class="ml-1">
          Publish this project
        </label>
      </div>
    </div>
  </div>
  <div class="mt-2">
    <%= f.text_area :body, class: "form-field", rows: 5 %>
  </div>
  <%= f.input :live_link, label: false, placeholder: "project's live link",
                  wrapper_html: { class: "mt-3" },
                  input_html: { class: "form-field" } %>
  <%= f.input :staging_link, label: false, placeholder: "project's staging link",
                  wrapper_html: { class: "mt-3" },
                  input_html: { class: "form-field" } %>
  <div class="flex items-center mt-3">
    <div class="flex mt-3">
      <label for="image" class="mr-2 text-white">Image:</label>
      <%= f.file_field :image, class: "text-white" %>
    </div>
    <%= f.input :position, required: true,
                  wrapper_html: { class: "mt-2" },
                  input_html: { class: "form-select-field w-20 ml-2" } %>
  </div>
  <div class="mt-4">
    <div class="flex gap-2">
      <%= f.input :technology_ids, as: :select,
                  collection: Technology.all.collect { |t| [t.name, t.id] },
                  include_blank: false, label: "Select technologies used during this project",
                  wrapper_html: { class: "flex flex-col mr-4 w-full" },
                  label_html: { class: "form-label" },
                  error_html: { class: "form-field-error" },
                  input_html: { class: "form-select-field w-full", multiple: true,
                                data: { controller: 'slim-select', slim_select_target: 'field' }} %>
    </div>
  </div>
  <%= f.submit "Save Portfolio", class: "submit-btn ml-2 mt-4" %>
<% end %>

app/views/dashboard/portfolios/_portfolio.html.erb
<div class="mb-10">
  <div class="flex flex-col md:flex-row justify-between mb-4 <%= portfolio.position.even? ? 'md:flex-row-reverse' : '' %>">
    <div class="w-1/4 p-2 text-center">
      <% if portfolio.image.attached? %>
        <%= image_tag portfolio.image.variant(:thumb) %>
        <%= button_to purge_attachment_path(portfolio.image.id), method: :delete, remote: true,
            class: "text-red-800 mr-4 pt-2", form: { data: { turbo_confirm: 'Are you sure?' } } do %>
          <%= heroicon "trash", options: { class: "w-4 text-red-900", disable_default_class: true } %>
        <% end %>
      <% else %>
        <%= image_tag "http://via.placeholder.com/300x200"  %>
      <% end %>
    </div>
    <div class="w-3/4 p-2">
      <div class="text-left">
        <div class="flex items-center">
          <h3 class="text-xl"><%= portfolio.title %></h3>
          <span class="ml-4">
            <%= link_to edit_dashboard_portfolio_path(portfolio), class: "admin-link" do %>
              <%= heroicon "pencil-square", options: { class: "w-4 text-blue-600 hover:text-blue-300",
                                        disable_default_class: true } %>
            <% end %>
          </span>
        </div>
        <h6><%= portfolio.subtitle %></h6>
        <p><%=h truncate(portfolio.body, :length => 245) %></p>
      </div>
      <div class="flex justify-between items-center <%= portfolio.position.even? ? 'flex-row-reverse' : '' %> mt-4">
        <div>
          <% portfolio.technologies.limit(5).each do |tech| %>
            <span class="font-small text-xs inline-block py-1 px-2 rounded text-slate-900 bg-slate-300 mr-1">
              <%= tech.name %>
            </span>
          <% end %>
        </div>
        <div class="flex gap-x-2 <%= portfolio.position.even? ? '' : 'justify-end' %>">
          <%= link_to "Show - ", dashboard_portfolio_path(portfolio), class: "text-sm text-amber-900 hover:underline" %>
          <%= link_to "View on Website - ", website_portfolio_path(portfolio), class: "text-sm text-amber-900 hover:underline", target: "_blank" if portfolio.published? %>
          <%= link_to "Live", portfolio.live_link, class: "text-sm text-amber-900 hover:underline", target: "_blank" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/portfolios/edit.html.erb
<div class="md:flex justify-between items-center mt-2 p-3">
  <%= render "form", portfolio: @portfolio %>
</div>

app/views/dashboard/portfolios/index.html.erb
<div class="flex-col p-4 pt-7 mt-3">
  <div class="flex justify-between items-center mb-2 text-sm font-medium">
    <div>
      <h1>Portfolio</h1>
    </div>
    <div>
      <%= link_to "+ New portfolio", new_dashboard_portfolio_path,
          class: "ml-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
    </div>
  </div>
</div>
<div class="flex-col p-4 pt-7 mt-3">
  <div class="mx-auto max-w-3xl">
    <%= render  @portfolios %>
  </div>
</div>

app/views/dashboard/portfolios/new.html.erb
<div class="mt-2 p-3">
  <%= render "form" %>
</div>

app/views/dashboard/portfolios/show.html.erb
<div class="flex-col p-4 pt-7 mt-3">
  <div class="my-32 px-2">
    <div class="flex justify-end gap-x-4 mx-auto max-w-4xl mb-2">
      <%= link_to "website link", website_portfolio_path(@portfolio), class: "admin-link", target: "_blank" %>
      <%#= render(Atoms::Links::LinkComponent.new(link_path: edit_admin_portfolio_path(@portfolio)).with_content("Edit")) %>
    </div>
    <div class="mx-auto max-w-4xl bg-white text-gray-900 p-4">
      <div class="flex justify-center">
        <% if @portfolio.image.attached? %>
          <%= image_tag @portfolio.image  %>
        <% else %>
          <%= image_tag "http://via.placeholder.com/600x400"  %>
        <% end %>
      </div>
      <div class="flex justify-end items-center gap-x-4 mt-2">
        <div>
          <% if @portfolio.staging_link.present? %>
            See staging project
            <%= link_to @portfolio.staging_link, target: "_blank", class: "text-amber-900" do %>
              <div style="width: 30px;"><%= heroicon "arrow-long-right", options: { class: "text-amber-900" } %></div>
            <% end %>
          <% end %>
        </div>
        <div>
          <% if @portfolio.live_link.present? %>
            See live project
            <%= link_to @portfolio.live_link, target: "_blank", class: "text-amber-900" do %>
              <div style="width: 30px;"><%= heroicon "arrow-long-right", options: { class: "text-amber-900" } %></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <h1 class="mt-20 mb-3 text-xl font-semibold"><%= @portfolio.title %></h1>
      <div class="mb-3">
        <em><%= @portfolio.subtitle %></em>
      </div>
      <p><%= @portfolio.body%></p>
      <h3 class="mt-10 mb-2 text-base font-semibold">Technologies Used:</h3>
      <% @portfolio.technologies.each do |t| %>
        <span class="text-xs font-semibold inline-block py-1 px-2 rounded text-slate-900 bg-slate-300 mr-1">
          <%= t.name %>
        </span>
      <% end %>
      <div class="flex gap-x-3 items-center mt-10">
        <%= render partial: "shared/display_attachments", locals: { attachments: @portfolio.photos } %>
      </div>
    </div>
  </div>
</div>