config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  # Defines the root path route ("/")
  root "website/pages#homepage"

  namespace :admin, path: "/admin" do
    get "/", to: "pages#home"
    resources :contacts
    resources :users
  end

  namespace :dashboard, path: "/dashboard" do
    get "/", to: "pages#home"
    resources :blog_posts
    resources :portfolios
    resources :tags
    resources :tasks
    resources :technologies
    resources :users, only: %i[show edit]
  end

  namespace :website, path: "/" do
    get "/", to: "pages#homepage"
    get    "/blog"          => "blog_posts#index"
    get    "/blog/:id"      => "blog_posts#show", as: :show_blog
    resources :contacts, only: %i[new create]
    resources :portfolios, only: %i[index show]
  end

  # ATTACHMENTS
  delete "attachments/:id/purge", to: "attachments#purge", as: :purge_attachment
  get "attachments/:id", to: "attachments#show", as: :show_attachment
end

app/models/portfolio.rb
# frozen_string_literal: true

class Portfolio < ApplicationRecord
  include Placeholder

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :subtitle, :body, :position

  belongs_to :user

  has_and_belongs_to_many :technologies

  scope :for_user, ->(user_id) { where(user_id: user_id) }

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 200]
  end

  has_many_attached :photos

  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs["name"].blank? }

  scope :published, -> { where(published: true) }

  def should_generate_new_friendly_id?
    title_changed?
  end
end

# == Schema Information
#
# Table name: portfolios
#
#  id           :bigint           not null, primary key
#  body         :text
#  live_link    :string
#  position     :integer
#  published    :boolean          default(FALSE)
#  slug         :string
#  staging_link :string
#  subtitle     :string
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_portfolios_on_slug     (slug) UNIQUE
#  index_portfolios_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

app/controllers/dashboard/portfolios_controller.rb
# frozen_string_literal: true

module Dashboard
  class PortfoliosController < ApplicationController
    layout "dashboard"

    before_action :authenticate_user!
    before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

    def index
      @portfolios = Portfolio.for_user(current_user.id).includes([:technologies]).order(:position)
    end

    def new
      @portfolio = Portfolio.new
    end

    def create
      @portfolio = Portfolio.new(portfolio_params)

      if @portfolio.save
        redirect_to dashboard_portfolios_path, notice: "Your Portfolio has been added."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def show
    end

    def update
      respond_to do |format|
        if @portfolio.update(portfolio_params)
          format.html { redirect_to dashboard_portfolio_path(@portfolio), notice: "Your Portfolio has been updated." }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @portfolio.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_portfolios_path, notice: "The Portfolio has been deleted!" }
      end
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :image,
        :live_link,
        :staging_link,
        :published,
        :position,
        :user_id,
        technology_ids: [],
        technologies_attributes: [:name]
      )
    end
  end
end

app/controllers/website/blog_posts_controller.rb
# frozen_string_literal: true

class Website::BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.published
  end

  def show
    @blog_post = BlogPost.friendly.find(params[:id])
  end
end

app/controllers/website/contacts_controller.rb
# frozen_string_literal: true

class Website::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: "Message sent. I will get back to you as soon as possible."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(
      :name,
      :email,
      :phone_number,
      :origin,
      :message
    )
  end
end

app/controllers/website/pages_controller.rb
# frozen_string_literal: true

class Website::PagesController < ApplicationController
  def homepage
  end
end

app/controllers/website/portfolios_controller.rb
# frozen_string_literal: true

module Website
  class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: [:show]

    def index
      @portfolios = Portfolio.published.includes([:technologies]).order(:position)
    end

    def show
    end

    private

    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end
  end
end

app/views/website/portfolios/_portfolio.html.erb
<div class="mb-20">
  <div class="flex flex-col md:flex-row justify-between mb-4 <%= portfolio.position.even? ? 'md:flex-row-reverse' : '' %>">
    <div class="md:w-1/4 p-2 text-center">
      <% if portfolio.image.attached? %>
        <%= image_tag portfolio.image.variant(:thumb) %>
      <% else %>
        <%= image_tag "http://via.placeholder.com/300x200"  %>
      <% end %>
    </div>
    <div class="md:w-3/4 p-2">
      <div class="text-left">
        <h3 class="text-2xl font-light"><%= portfolio.title %></h3>
        <h6 class="text-md italic mb-2"><%= portfolio.subtitle %></h6>
        <p><%=h truncate(portfolio.body, :length => 245) %></p>
      </div>
      <div class="flex flex-col md:flex-row justify-between items-center <%= portfolio.position.even? ? 'flex-row-reverse' : '' %> mt-4">
        <div>
          <% portfolio.technologies.limit(5).each do |tech| %>
            <span class="font-small text-xs inline-block py-1 px-2 rounded text-slate-900 bg-slate-300 mr-1">
              <%= tech.name %>
            </span>
          <% end %>
        </div>
        <div class="flex gap-x-2 <%= portfolio.position.even? ? '' : 'justify-end' %> mt-4 md:mt-0">
          <%= link_to "View", website_portfolio_path(portfolio), class: "text-sm text-amber-900 hover:underline" %>
          <%= link_to "Staging", portfolio.staging_link, target: "_blank", class: "text-sm text-amber-900 hover:underline" if portfolio.staging_link.present? %>
          <%= link_to "Live", portfolio.live_link, target: "_blank", class: "text-sm text-amber-900 hover:underline" if portfolio.live_link.present? %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/website/portfolios/index.html.erb
<div class="flex flex-col justify-center items-center text-center mx-auto max-w-3xl my-16 p-16">
  <div class="mt-22">
    <h1 class="text-4xl font-light">Some Things I've Built</h1>
    <p class="mt-6">
      List of few projects I worked on below.
    </p>
    <p>
      With details about what was done and what tools were used.
    </p>
  </div>
  <div class="mt-10">
    <%= link_to  "Let's work on yours", new_website_contact_path,
        class: "web-submit-btn" %>
  </div>
</div>
<div class="flex flex-col justify-center items-center text-center mx-auto max-w-4xl md:my-16 md:p-16">
  <%= render  @portfolios %>
</div>

app/views/website/portfolios/show.html.erb
<div class="my-32 px-2 text-slate-900">
  <div class="mx-auto max-w-4xl p-4">
    <div class="flex justify-center">
      <% if @portfolio.image.attached? %>
        <%= image_tag @portfolio.image %>
      <% else %>
        <%= image_tag "http://via.placeholder.com/600x400" %>
      <% end %>
    </div>
    <div class="flex justify-end items-center gap-x-4 mt-2">
      <div>
        <% if @portfolio.staging_link.present? %>
          See staging project
          <%= link_to @portfolio.staging_link, target: "_blank", class: "text-amber-900" do %>
            <div style="width: 30px;"><%= heroicon "arrow-long-right", options: { class: "text-amber-900" } %></div>
          <% end %>
        <% end %>
      </div>
      <div>
        <% if @portfolio.live_link.present? %>
          See live project
          <%= link_to @portfolio.live_link, target: "_blank", class: "text-amber-900" do %>
            <div style="width: 30px;"><%= heroicon "arrow-long-right", options: { class: "text-amber-900" } %></div>
          <% end %>
        <% end %>
      </div>
    </div>
    <h1 class="mt-20 mb-3 text-xl font-semibold"><%= @portfolio.title %></h1>
    <div class="mb-3">
      <em><%= @portfolio.subtitle %></em>
    </div>
    <p><%= @portfolio.body %></p>
    <h3 class="mt-10 mb-2 text-base font-semibold">Technologies Used:</h3>
    <% @portfolio.technologies.each do |t| %>
      <span class="font-small text-xs inline-block py-1 px-2 rounded bg-slate-300 mr-1">
        <%= t.name %>
      </span>
    <% end %>

    <div class="flex gap-x-3 items-center mt-10">
      <% if @portfolio.photos.attached? %>
        <% @portfolio.photos.includes(:blob).each do |photo| %>
          <%= link_to show_attachment_path(photo), class: "", data: { turbo_frame: "modal" } do %>
            <%= image_tag photo, class: "w-32" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>